Make blockinfile work with python3
    Traceback (most recent call last):
      File \"/tmp/ansible_ueg52c0b/ansible_module_blockinfile.py\", line 319, in <module>
        main()
      File \"/tmp/ansible_ueg52c0b/ansible_module_blockinfile.py\", line 259, in main
        if line.startswith(marker0):
    TypeError: startswith first arg must be bytes or a tuple of bytes, not str

Also clean imports while on it.

(cherry picked from commit 3db76b820718450e49ccb1880b9f9323ead3bab0)