Fix pkgng on python 3
Fail with:

    Traceback (most recent call last):
      File \"/tmp/ansible_2rsl4fg1/ansible_module_pkgng.py\", line 353, in <module>
        main()
      File \"/tmp/ansible_2rsl4fg1/ansible_module_pkgng.py\", line 330, in main
        _changed, _msg = install_packages(module, pkgng_path, pkgs, p[\"cached\"], p[\"pkgsite\"], dir_arg)
      File \"/tmp/ansible_2rsl4fg1/ansible_module_pkgng.py\", line 161, in install_packages
        old_pkgng = pkgng_older_than(module, pkgng_path, [1, 1, 4])
      File \"/tmp/ansible_2rsl4fg1/ansible_module_pkgng.py\", line 121, in pkgng_older_than
        while compare_version[i] == version[i]:
    TypeError: 'map' object is not subscriptable

(cherry picked from commit 65ba526c9f9a37d28d7842b9912dd6deb7c19c6b)